### ISSUE TITLE
Crashing with act order and no act order since latest changes.

### ISSUE THREAD

**Issue by disarmyouwitha** [turboderp/exllama#1]
Crashing with act order and no act order since latest changes.

`python test_benchmark_inference.py -t /home/nap/llm_models/koala-13B-HF-4bit/tokenizer.model -c /home/nap/llm_models/koala-13B-HF-4bit/config.json -m /home/nap/llm_models/koala-13B-HF-4bit/koala13B-4bit-128g-no-act-order.safetensors -g 128 -p -ppl

Using /home/nap/.cache/torch_extensions/py310_cu118 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/nap/.cache/torch_extensions/py310_cu118/exllama_ext/build.ninja...
Building extension module exllama_ext...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module exllama_ext...
 -- Loading model
 -- Tokenizer: /home/nap/llm_models/koala-13B-HF-4bit/tokenizer.model
 -- Model config: /home/nap/llm_models/koala-13B-HF-4bit/config.json
 -- Model: /home/nap/llm_models/koala-13B-HF-4bit/koala13B-4bit-128g-no-act-order.safetensors
 -- Groupsize: 128
 -- Sequence length: 2048
 -- Options: ['attention: pytorch_scaled_dp', 'matmul: switched', 'perf', 'ppl']
 ** Time, Load model: 1.50 seconds
 ** VRAM, Model: [cuda:0] 6,689.96 MB
 -- Inference, first pass.
Traceback (most recent call last):
  File "/home/nap/Documents/exllama-api/test_benchmark_inference.py", line 153, in <module>
    logits = timer("Inference", lambda: wrapper.next_logits(ids))
  File "/home/nap/Documents/exllama-api/test_benchmark_inference.py", line 64, in timer
    ret = func()
  File "/home/nap/Documents/exllama-api/test_benchmark_inference.py", line 153, in <lambda>
    logits = timer("Inference", lambda: wrapper.next_logits(ids))
  File "/home/nap/Documents/exllama-api/test_benchmark_inference.py", line 54, in next_logits
    return self.model.forward(input_ids, self.cache, last_id_only)
  File "/home/nap/Documents/exllama-api/model.py", line 523, in forward
    hidden_states = decoder_layer(hidden_states, cache, attn_masks[device])
  File "/home/nap/miniconda3/envs/exllama/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nap/miniconda3/envs/exllama/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nap/Documents/exllama-api/model.py", line 351, in forward
    hidden_states = self.self_attn(hidden_states, cache, attention_mask)
  File "/home/nap/miniconda3/envs/exllama/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nap/miniconda3/envs/exllama/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nap/Documents/exllama-api/model.py", line 264, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.config.num_attention_heads, self.config.head_dim).transpose(1, 2)
  File "/home/nap/miniconda3/envs/exllama/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nap/miniconda3/envs/exllama/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nap/Documents/exllama-api/model.py", line 148, in forward
    out = quant_util.matmul4bit(x,
  File "/home/nap/Documents/exllama-api/quant_util.py", line 70, in matmul4bit
    if switch: output = _q4v2_recons(x, qweight, scales, zeros, groupsize, g_idx)
  File "/home/nap/Documents/exllama-api/quant_util.py", line 51, in _q4v2_recons
    q4v2_recons(qweight, buffer, scales, zeros, groupsize, g_idx if g_idx is not None else none_tensor)
TypeError: q4v2_recons(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor, arg3: torch.Tensor, arg4: int) -> None

Invoked with: tensor([[-1398026309,  1248440250,  1968657271,  ...,  1648788836,
          1771582072,  1432982596],
        [-1129530164, -1402287736,  1970562646,  ...,  2016756323,
           900172105, -2007726747],
        [ -876888900, -1735723655,  1717986149,  ..., -1236974524,
          1117231658, -1988663128],
        ...,
        [ 2125380013,   729121940, -1516013256,  ..., -1448441238,
          1395411286,  -910718291],
        [ -609454181, -1721358701,  2071349639,  ..., -1380296262,
           842437924,  -646359431],
        [ 1518767014, -1668986954, -1201825385,  ...,  1920967637,
          1770408276,  -932611670]], device='cuda:0', dtype=torch.int32), tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0', dtype=torch.float16), tensor([[0.0146179199, 0.0079727173, 0.0102233887,  ..., 0.0184173584,
         0.0107421875, 0.0127944946],
        [0.0070610046, 0.0054702759, 0.0059432983,  ..., 0.0166778564,
         0.0122299194, 0.0089492798],
        [0.0113754272, 0.0084228516, 0.0120010376,  ..., 0.0273590088,
         0.0140762329, 0.0107803345],
        ...,
        [0.0120925903, 0.0055465698, 0.0123825073,  ..., 0.0216217041,
         0.0121994019, 0.0125427246],
        [0.0135955811, 0.0066719055, 0.0160827637,  ..., 0.0184020996,
         0.0138168335, 0.0129928589],
        [0.0071449280, 0.0064125061, 0.0047798157,  ..., 0.0156250000,
         0.0118713379, 0.0109329224]], device='cuda:0', dtype=torch.float16), tensor([[ 2023392650,  1010177125, -1289406317,  ...,  1279628968,
         -2103822205,  1447265365],
        [ 2002999416,  1783731782,  1698252904,  ...,  1971681173,
         -2055768200,  1720019317],
        [-2023401052,   678589785, -1808521094,  ...,  1430677867,
         -2089273206,  1750898759],
        ...,
        [ 1703449704,  1770349877, -1807272091,  ..., -2041219240,
          1732671894,  1721131894],
        [ 1732459378,  1197652024,  1950771288,  ..., -1837668746,
          1719236473, -2024245130],
        [-2005375383,  1970881927,  1753777765,  ...,  1971808872,
          2003334805,  1970759287]], device='cuda:0', dtype=torch.int32), 128, tensor([ 0,  0,  0,  ..., 39, 39, 39], device='cuda:0', dtype=torch.int32)`

Reverting to previous commit fixed the issue for me.

**Comment by disarmyouwitha** [comment]
False Alarm. Not sure what was going on, but a fresh git pull solved everything.

**Comment by turboderp** [comment]
Don't spend too much time on it, I'm committing some big changes to the act-order stuff soon. Big optimization with lots of room for new bugs. :)
