### ISSUE TITLE
Expected size 2048 but got size ...

### ISSUE THREAD

**Issue by Jeduh** [turboderp/exllama#127]
```
python3 test_benchmark_inference.py -d ../data/model/ -ppl -ppl_ds datasets/wikitext2.txt -ppl_cn 40 -l 4096 -ppl_cs 4096 -ppl_ct 4096 -cpe 2
 -- Perplexity:
 -- - Dataset: datasets/wikitext2.txt
 -- - Chunks: 40
 -- - Chunk size: 4096 -> 4096
 -- - Chunk overlap: 0
 -- - Min. chunk size: 50
 -- - Key: text
 -- Tokenizer: ../data/model/tokenizer.model
 -- Model config: ../data/model/config.json
 -- Model: ../data/model/model.safetensors
 -- Sequence length: 4096
 -- RoPE compression factor: 2.0
 -- Tuning:
 -- --matmul_recons_thd: 8
 -- --fused_mlp_thd: 2
 -- --sdp_thd: 8
 -- Options: ['perplexity']
 ** Time, Load model: 3.48 seconds
 ** Time, Load tokenizer: 0.01 seconds
 -- Groupsize (inferred): 128
 -- Act-order (inferred): no
 ** VRAM, Model: [cuda:0] 3,639.47 MB
 -- Loading dataset...
 -- Testing 40 chunksTraceback (most recent call last):
  File "/app/test_benchmark_inference.py", line 212, in <module>
    ppl.test(args.perplexity_chunk_num,
  File "/app/perplexity.py", line 118, in test
    logits = self._next_logits(input_ids, lora, last_id_only = False)
  File "/app/perplexity.py", line 45, in _next_logits
    return self.model.forward(input_ids, self.cache, last_id_only, lora = apply_lora)
  File "/app/model.py", line 855, in forward
    result = r if result is None else torch.cat((result, r), dim = -1)
RuntimeError: Sizes of tensors must match except in dimension 2. Expected size 2048 but got size 1265 for tensor number 1 in the list.

```

The command used to work before I updated from a few days old version, what might be the issue?

**Comment by turboderp** [comment]
It was a typo. Think I fixed it now.

**Comment by Jeduh** [comment]
Thanks again turbo :)

**Comment by Jeduh** [comment]
Fixed
