### ISSUE TITLE
LoRA and dual GPU

### ISSUE THREAD

**Issue by juanps90** [turboderp/exllama#140]
I've been trying to use exllama with a LoRA, and it works until the following lines are added:

```
config.gpu_peer_fix = True
config.set_auto_map("10,24")
```
Which return the following error:

```
Exception has occurred: RuntimeError
CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
  File ".../exllama/model.py", line 722, in __init__
    tensor = tensor.to(device, non_blocking = True)
  File ".../exllama/example_lora.py", line 37, in <module>
    model = ExLlama(config)                                 # create ExLlama instance and load the weights
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
How should I run exllama with dual GPUs and LoRA support?

**Comment by turboderp** [comment]
Do you have a more complete code example? The error indicates that he model is being loaded incorrectly before it even gets to loading the LoRA.

**Comment by juanps90** [comment]
Sorry, I made a mistake. Also, the original issue lacks details, I hope the following can help.

I am using alpha scaling for longer context. In this example I use a context length of 3000 so it fits a single GPU.

```
config = ExLlamaConfig(model_config_path)               # create config from config.json
config.model_path = model_path                          # supply path to model weights file
config.alpha_value = 2
config.max_seq_len = 3000


config.gpu_peer_fix = True
config.set_auto_map("10,24")
```
It crashes with the following error:

```
 --- LoRA ----------------- 

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/asd/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/asd/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/asd/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/asd/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/asd/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/asd/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/asd/pytests/exllama/example_lora.py", line 78, in <module>
    output = generator.generate_simple(prompt, max_new_tokens = 1200)
  File "/home/asd/pytests/exllama/generator.py", line 307, in generate_simple
    token = self.gen_single_token()
  File "/home/asd/pytests/exllama/generator.py", line 326, in gen_single_token
    logits = self.model.forward(self.sequence[:, -1:], self.cache, lora = self.lora)
  File "/home/asd/pytests/exllama/model.py", line 849, in forward
    r = self._forward(input_ids[:, chunk_begin : chunk_end],
  File "/home/asd/pytests/exllama/model.py", line 928, in _forward
    hidden_states = _move_tensor(hidden_states, device, "hidden_states", self.config)
  File "/home/asd/pytests/exllama/model.py", line 630, in _move_tensor
    return tensor.to(new_device)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

But with the following configuration:

```
config.alpha_value = 2
config.max_seq_len = 3000

# The following lines have been commented out
#config.gpu_peer_fix = True
#config.set_auto_map("10,24")
```

The example_lora.py runs with no issues.

**Comment by turboderp** [comment]
I just pushed a change that should fix #141. Could you try that and see if it also helps here?
