### ISSUE TITLE
`cuda_runtime_api.h` not found

### ISSUE THREAD

**Issue by vadi2** [turboderp/exllama#142]
Using Ubuntu 22.04 LTS, the install instructions work fine but the benchmarking scripts fails to find the cuda runtime headers. What could be wrong?

```bash
(exllama) vadi@barbar:~/Programs/exllama$ pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cu118
Looking in indexes: https://download.pytorch.org/whl/nightly/cu118
Requirement already satisfied: torch in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (2.1.0.dev20230708+cu118)
Requirement already satisfied: filelock in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from torch) (3.9.0)
Requirement already satisfied: typing-extensions in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from torch) (4.4.0)
Requirement already satisfied: sympy in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from torch) (1.11.1)
Requirement already satisfied: networkx in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from torch) (3.0rc1)
Requirement already satisfied: jinja2 in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from torch) (2023.4.0)
Requirement already satisfied: pytorch-triton==2.1.0+440fd1bf20 in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from torch) (2.1.0+440fd1bf20)
Requirement already satisfied: MarkupSafe>=2.0 in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from jinja2->torch) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from sympy->torch) (1.2.1)
(exllama) vadi@barbar:~/Programs/exllama$ pip install -r requirements.txt
Requirement already satisfied: torch>=2.0.1 in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (2.1.0.dev20230708+cu118)
Requirement already satisfied: safetensors==0.3.1 in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (0.3.1)
Requirement already satisfied: sentencepiece>=0.1.97 in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (0.1.99)
Requirement already satisfied: ninja==1.11.1 in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (1.11.1)
Requirement already satisfied: filelock in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from torch>=2.0.1->-r requirements.txt (line 1)) (3.9.0)
Requirement already satisfied: typing-extensions in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from torch>=2.0.1->-r requirements.txt (line 1)) (4.4.0)
Requirement already satisfied: sympy in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from torch>=2.0.1->-r requirements.txt (line 1)) (1.11.1)
Requirement already satisfied: networkx in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from torch>=2.0.1->-r requirements.txt (line 1)) (3.0rc1)
Requirement already satisfied: jinja2 in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from torch>=2.0.1->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: fsspec in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from torch>=2.0.1->-r requirements.txt (line 1)) (2023.4.0)
Requirement already satisfied: pytorch-triton==2.1.0+440fd1bf20 in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from torch>=2.0.1->-r requirements.txt (line 1)) (2.1.0+440fd1bf20)
Requirement already satisfied: MarkupSafe>=2.0 in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from jinja2->torch>=2.0.1->-r requirements.txt (line 1)) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from sympy->torch>=2.0.1->-r requirements.txt (line 1)) (1.2.1)
(exllama) vadi@barbar:~/Programs/exllama$ python test_benchmark_inference.py -d ~/Programs/wizard-vicuna-13B-SuperHOT-8K-GGML/ -p -ppl
Traceback (most recent call last):
  File "/home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    subprocess.run(
  File "/home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vadi/Programs/exllama/test_benchmark_inference.py", line 1, in <module>
    from model import ExLlama, ExLlamaCache, ExLlamaConfig
  File "/home/vadi/Programs/exllama/model.py", line 12, in <module>
    import cuda_ext
  File "/home/vadi/Programs/exllama/cuda_ext.py", line 43, in <module>
    exllama_ext = load(
  File "/home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1301, in load
    return _jit_compile(
  File "/home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1524, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1639, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1932, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'exllama_ext': [1/11] /usr/bin/nvcc  -DTORCH_EXTENSION_NAME=exllama_ext -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/vadi/Programs/exllama/exllama_ext -isystem /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages/torch/include -isystem /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages/torch/include/TH -isystem /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages/torch/include/THC -isystem /home/vadi/Programs/miniconda3/envs/exllama/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -lineinfo -std=c++17 -c /home/vadi/Programs/exllama/exllama_ext/cuda_func/rms_norm.cu -o rms_norm.cuda.o 
FAILED: rms_norm.cuda.o 
/usr/bin/nvcc  -DTORCH_EXTENSION_NAME=exllama_ext -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/vadi/Programs/exllama/exllama_ext -isystem /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages/torch/include -isystem /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages/torch/include/TH -isystem /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages/torch/include/THC -isystem /home/vadi/Programs/miniconda3/envs/exllama/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -lineinfo -std=c++17 -c /home/vadi/Programs/exllama/exllama_ext/cuda_func/rms_norm.cu -o rms_norm.cuda.o 
<command-line>: fatal error: cuda_runtime.h: No such file or directory
```

**Comment by turboderp** [comment]
Do you have CUDA-toolkit installed?

**Comment by vadi2** [comment]
I do, I installed it straight [from NVIDIA](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_local) and it's in `/usr/local/cuda-12.2`:

```
$ ls /usr/local/cuda-12.2
bin  compute-sanitizer  doc  DOCS  EULA.txt  extras  gds  include  lib64  libnvvp  nsightee_plugins  nvml  nvvm  README  res  share  src  targets  tools  version.json
```

**Comment by jmoney7823956789378** [comment]
Is `$CUDA_HOME` set?

**Comment by vadi2** [comment]
That was it! Thanks. I've set it and got past that error. Have a new one now, filed separately as https://github.com/turboderp/exllama/issues/143.
