### ISSUE TITLE
temp_state buffer is too small when running in batch_mode, happens only when one sequence/input is empty

### ISSUE THREAD

**Issue by nikshepsvn** [turboderp/exllama#160]
'']: temp_state buffer is too small
Traceback (most recent call last):
  File "/root/pulsar/pulsar/api/worker.py", line 105, in process_batch
    generated_responses = self.respond_batch(
  File "/root/pulsar/pulsar/api/batch.py", line 79, in respond_batch
    raise e
  File "/root/pulsar/pulsar/api/batch.py", line 70, in respond_batch
    generated_text = generator.generate_response(
  File "/root/pulsar/pulsar/generator.py", line 312, in generate_response
    self.gen_begin(ids)
  File "/root/pulsar/pulsar/generator.py", line 177, in gen_begin
    self.model.forward(
  File "/root/pulsar/pulsar/model.py", line 1130, in forward
    r = self._forward(
  File "/root/pulsar/pulsar/model.py", line 1226, in _forward
    hidden_states = decoder_layer.forward(
  File "/root/pulsar/pulsar/model.py", line 609, in forward
    hidden_states = self.mlp.forward(hidden_states, buffer, lora)
  File "/root/pulsar/pulsar/model.py", line 295, in forward
    y = self.down_proj.forward(y, lora)
  File "/root/pulsar/pulsar/model.py", line 208, in forward
    out = cuda_ext.ext_q4_matmul(x, self.q4, self.width)
  File "/root/pulsar/pulsar/cuda_ext.py", line 105, in ext_q4_matmul
    q4_matmul(x, q4, output)
RuntimeError: temp_state buffer is too small

Been trying to debug the above but can't figure out what's going on, getting errors when input is something like ['', 'test'] to the generate_response function (which is generate_simple with more stop_condition checks etc.)

**Comment by nikshepsvn** [comment]
RuntimeError: temp_state buffer is too small
2023-07-17 16:12:08,630:ERROR - Error processing input ['', '']: temp_state buffer is too small
Traceback (most recent call last):
  File "/root/pulsar/pulsar/api/worker.py", line 105, in process_batch
    generated_responses = self.respond_batch(
  File "/root/pulsar/pulsar/api/batch.py", line 79, in respond_batch
    raise e
  File "/root/pulsar/pulsar/api/batch.py", line 70, in respond_batch
    generated_text = generator.generate_response(
  File "/root/pulsar/pulsar/generator.py", line 312, in generate_response
    self.gen_begin(ids)
  File "/root/pulsar/pulsar/generator.py", line 177, in gen_begin
    self.model.forward(
  File "/root/pulsar/pulsar/model.py", line 1130, in forward
    r = self._forward(
  File "/root/pulsar/pulsar/model.py", line 1226, in _forward
    hidden_states = decoder_layer.forward(
  File "/root/pulsar/pulsar/model.py", line 609, in forward
    hidden_states = self.mlp.forward(hidden_states, buffer, lora)
  File "/root/pulsar/pulsar/model.py", line 295, in forward
    y = self.down_proj.forward(y, lora)
  File "/root/pulsar/pulsar/model.py", line 208, in forward
    out = cuda_ext.ext_q4_matmul(x, self.q4, self.width)
  File "/root/pulsar/pulsar/cuda_ext.py", line 105, in ext_q4_matmul
    q4_matmul(x, q4, output)
RuntimeError: temp_state buffer is too small

**Comment by nikshepsvn** [comment]
for context, im running on a 24GB card with max_seq_len set to 8k and a batch_size of 2

**Comment by turboderp** [comment]
I can't seem to reproduce this. Do you have a complete example that I could debug?

**Comment by turboderp** [comment]
I'll assume this is the same issue as #211 and close it for now.
