### ISSUE TITLE
Are you able to help?

### ISSUE THREAD

**Issue by NO-ob** [turboderp/exllama#17]
I've been trying to setup exllama with my webserver. it will create an instance of the LlamaModelRepo and call loadModel, if I use the following code, i can get text output fine
```
class LlamaModelRepo:
    tokenizer: ExLlamaTokenizer = None
    generator: ExLlamaGenerator = None
    config: ExLlamaConfig = None
    model: ExLlama = None
    cache: ExLlamaCache = None
    def __init__(self):
        self.models: list = []
        self.modelsDir: str = './models'

    def loadModel(self, llamaModel: LlamaModel):
        errors = []
        configPath = llamaModel.path + "/config.json"
        if (not exists(configPath)):
            errors.append(f"{configPath} does not exist")
        
        modelPath = llamaModel.path + "/" + llamaModel.modelFile
        if (not exists(modelPath)):
            errors.append(f"{modelPath} does not exist")
            
        tokenizerModelPath = llamaModel.path + "/tokenizer.model"
        if (not exists(tokenizerModelPath)):
            errors.append(f"{tokenizerModelPath} does not exist")

        if errors:
            raise Exception("\n".join(errors))
        
        torch.set_grad_enabled(False)
        torch.cuda._lazy_init()
        self.config = ExLlamaConfig(configPath)
        self.config.model_path = modelPath
        self.config.max_seq_len = 2048
        self.model = ExLlama(self.config)
        self.cache = ExLlamaCache(self.model)

        self.tokenizer = ExLlamaTokenizer(tokenizerModelPath)
        self.generator = ExLlamaGenerator(self.model, self.tokenizer, self.cache)
        self.generator.settings.token_repetition_penalty_max = 1.2
        self.generator.settings.token_repetition_penalty_sustain = 20
        self.generator.settings.token_repetition_penalty_decay = 50
        gen_tokens = 200
        text = self.generator.generate_simple("test", max_new_tokens = 200)
        print(text)
```
Printed output 
```
test Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
Create a list of 5 adjectives to describe a car.

### Response:
1. Sleek
2. Powerful
3. Luxurious
4. Reliable
5. Sporty
```

If i move the bottom lines so they happen in a separate function, I call loadModel and then call chat through a separate request to the server. I get some exception, im very confused about why this is happening here and wondering if im doing something wrong?

```
class LlamaModelRepo:
    tokenizer: ExLlamaTokenizer = None
    generator: ExLlamaGenerator = None
    config: ExLlamaConfig = None
    model: ExLlama = None
    cache: ExLlamaCache = None
    def __init__(self):
        self.models: list = []
        self.modelsDir: str = './models'

    def loadModel(self, llamaModel: LlamaModel):
        errors = []
        configPath = llamaModel.path + "/config.json"
        if (not exists(configPath)):
            errors.append(f"{configPath} does not exist")
        
        modelPath = llamaModel.path + "/" + llamaModel.modelFile
        if (not exists(modelPath)):
            errors.append(f"{modelPath} does not exist")
            
        tokenizerModelPath = llamaModel.path + "/tokenizer.model"
        if (not exists(tokenizerModelPath)):
            errors.append(f"{tokenizerModelPath} does not exist")

        if errors:
            raise Exception("\n".join(errors))
        
        torch.set_grad_enabled(False)
        torch.cuda._lazy_init()
        self.config = ExLlamaConfig(configPath)
        self.config.model_path = modelPath
        self.config.max_seq_len = 2048
        self.model = ExLlama(self.config)
        self.cache = ExLlamaCache(self.model)

        self.tokenizer = ExLlamaTokenizer(tokenizerModelPath)
        self.generator = ExLlamaGenerator(self.model, self.tokenizer, self.cache)
        self.generator.settings.token_repetition_penalty_max = 1.2
        self.generator.settings.token_repetition_penalty_sustain = 20
        self.generator.settings.token_repetition_penalty_decay = 50
        gen_tokens = 200

    def chat(self, text: str, params:dict = {}):
        text = self.generator.generate_simple("test", max_new_tokens = 200)
        print(text)
```

exception 

```
Traceback (most recent call last):
  File "/home/kannalo/.local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kannalo/.local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kannalo/.local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kannalo/.local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kannalo/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kannalo/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/kanna/Documents/llm/exllama/server.py", line 110, in chat
    return modelRepo.chat(text="test")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/kanna/Documents/llm/exllama/repos/model_repo.py", line 97, in chat
    text = self.generator.generate_simple(text, max_new_tokens = 200)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/kanna/Documents/llm/exllama/generator.py", line 176, in generate_simple
    self.gen_begin(ids)
  File "/mnt/kanna/Documents/llm/exllama/generator.py", line 103, in gen_begin
    self.model.forward(self.sequence[:, :-1], self.cache, preprocess_only = True)
  File "/mnt/kanna/Documents/llm/exllama/model.py", line 1153, in forward
    hidden_states = decoder_layer.forward(hidden_states, cache, buffers[device])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/kanna/Documents/llm/exllama/model.py", line 540, in forward
    hidden_states = self.self_attn.forward(hidden_states, cache, buffer)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/kanna/Documents/llm/exllama/model.py", line 447, in forward
    query_states = self.q_proj.forward(hidden_states)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/kanna/Documents/llm/exllama/model.py", line 314, in forward
    out = cuda_ext.ExAutogradMatmul4bitCuda.apply(x, self.qweight, self.scales, self.qzeros, self.groupsize, self.bits, self.maxq)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kannalo/.local/lib/python3.11/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kannalo/.local/lib/python3.11/site-packages/torch/cuda/amp/autocast_mode.py", line 106, in decorate_fwd
    return fwd(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/kanna/Documents/llm/exllama/cuda_ext.py", line 271, in forward
    raise ValueError("Not implemented yet")
ValueError: Not implemented yet

```

**Comment by turboderp** [comment]
My guess would be that LoadModel gets called in a `with torch.no_grad()` scope, while the separate function doesn't. The error you're seeing is from running the forward pass with gradients enabled (i.e. for training), which currently isn't supported.

I'll add a check later today at the beginning of the forward pass to spit out a more descriptive error message.

**Comment by turboderp** [comment]
I'm not sure if `torch.set_grad_enabled(False)` does the same thing. You'd think so. But `torch.no_grad()` at least works, so I'd stick with that if you're not sure.

**Comment by NO-ob** [comment]
Thankyou
