### ISSUE TITLE
Can't apply loras on llama2

### ISSUE THREAD

**Issue by BadisG** [turboderp/exllama#171]
Hello,
I was trying to apply some loras on llama2-13b-chat with ooba's webui:
https://huggingface.co/Mikael110/llama-2-13b-guanaco-qlora
But I got this error,
```
2023-07-20 09:55:09 INFO:Applying the following LoRAs to Llama-2-13B-chat-GPTQ: llama-2-13b-guanaco-qlora
Traceback (most recent call last):
  File "C:\Users\Utilisateur\anaconda3\envs\textgen\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Utilisateur\anaconda3\envs\textgen\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\Utilisateur\anaconda3\envs\textgen\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\Utilisateur\anaconda3\envs\textgen\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\Utilisateur\anaconda3\envs\textgen\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\Utilisateur\anaconda3\envs\textgen\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Utilisateur\anaconda3\envs\textgen\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Utilisateur\anaconda3\envs\textgen\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Utilisateur\anaconda3\envs\textgen\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "D:\Large-Language-Models\text-generation-webui\server.py", line 83, in load_lora_wrapper
    add_lora_to_model(selected_loras)
  File "D:\Large-Language-Models\text-generation-webui\modules\LoRA.py", line 15, in add_lora_to_model
    add_lora_exllama(lora_names)
  File "D:\Large-Language-Models\text-generation-webui\modules\LoRA.py", line 52, in add_lora_exllama
    lora = ExLlamaLora(shared.model.ex_model, str(lora_config_path), str(lora_adapter_path))
  File "C:\Users\Utilisateur\anaconda3\envs\textgen\lib\site-packages\exllama\lora.py", line 113, in __init__
    else: raise ValueError(f" ## Error: unsupported tensor dtype in {self.lora_path}")
ValueError:  ## Error: unsupported tensor dtype in loras\llama-2-13b-guanaco-qlora\adapter_model.bin
```
Maybe it has to do with Exllama having some issues with the BFloat16 dtype and is not capable of converting it to Float16?

**Comment by turboderp** [comment]
It's not specific to Llama2 but to the LoRA. ExLlama could convert BF16 to FP16, it just doesn't at the moment. See: #170
