### ISSUE TITLE
Exllama tutorials?

### ISSUE THREAD

**Issue by NickDatLe** [turboderp/exllama#192]
I'm new to exllama, are there any tutorials on how to use this? I'm trying this with the llama-2 70b model.

**Comment by SinanAkkoyun** [comment]
There is no specific tutorial but here is how to set it up and get it running!
(note: for the 70B model you need at least 42GB VRAM, so a single A6000 / 6000 Ada or two 3090/4090s can only run the model, see the README for speed stats on a mixture of GPUs)

To begin with, you want to install conda [install script](https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh) and then create a new conda environment (so that pip packages don't mix with other py projects)
```sh
conda create -n exllama python=3.10
# after that
conda activate exllama
```

Then, clone the repo
```sh
git clone https://github.com/turboderp/exllama
cd exllama
```

You want to download a GPTQ quantized model. [TheBloke](https://huggingface.co/TheBloke/Llama-2-70B-chat-GPTQ) provides lots of them that all work.
```sh
# if you don't have git lfs installed: sudo apt install git-lfs
git lfs install
git clone https://huggingface.co/TheBloke/Llama-2-70B-chat-GPTQ
```

You're all set. Now, the only thing left is running a test benchmark and finally running the chatbot example.
```sh
python test_benchmark_inference.py -p -ppl -d ../path/to/Llama-2-70B-chat-GPTQ/
```

If that is successful, run this and enjoy a chatbot:
```sh
python example_chatbot.py -d ../path/to/Llama-2-70B-chat-GPTQ/ -un NickDatLe -bn ChadGPT -p prompt_chatbort.txt -nnl
# -nnl makes it so that the bot can output more than one line
```

Et voila. Edit the prompt_chatbort.txt inside the exllama repo as you like. Keep in mind, the Llama 2 chat format is different than the one the example provides, I am working on implementing the real prompt into `example_chatbot_llama2chat.py` and will do a PR soon.

**Comment by NickDatLe** [comment]
I have 2x 4090 GPU, it's only using one of them as far as I can tell, and so I'm getting a cuda out of memory error:

(py311) nick@easyai:~/dev/exllama$ python test_benchmark_inference.py -p -ppl -d Llama-2-70B-chat-GPTQ
 -- Perplexity:
 -- - Dataset: datasets/wikitext2_val_sample.jsonl
 -- - Chunks: 100
 -- - Chunk size: 2048 -> 2048
 -- - Chunk overlap: 0
 -- - Min. chunk size: 50
 -- - Key: text
 -- Tokenizer: Llama-2-70B-chat-GPTQ/tokenizer.model
 -- Model config: Llama-2-70B-chat-GPTQ/config.json
 -- Model: Llama-2-70B-chat-GPTQ/gptq_model-4bit--1g.safetensors
 -- Sequence length: 2048
 -- Tuning:
 -- --sdp_thd: 8
 -- --matmul_recons_thd: 8
 -- --fused_mlp_thd: 2
 -- Options: ['perf', 'perplexity']
Traceback (most recent call last):
  File "/home/nick/dev/exllama/test_benchmark_inference.py", line 125, in <module>
    model = timer("Load model", lambda: ExLlama(config))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nick/dev/exllama/test_benchmark_inference.py", line 56, in timer
    ret = func()
          ^^^^^^
  File "/home/nick/dev/exllama/test_benchmark_inference.py", line 125, in <lambda>
    model = timer("Load model", lambda: ExLlama(config))
                                        ^^^^^^^^^^^^^^^
  File "/home/nick/dev/exllama/model.py", line 831, in __init__
    tensor = tensor.to(device, non_blocking = True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB (GPU 0; 23.64 GiB total capacity; 23.23 GiB already allocated; 23.88 MiB free; 23.23 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

How do i split the model between the two GPUs?

**Comment by turboderp** [comment]
You need to define how weights are to be split across the GPUs. There's a bit of trial and error in that, currently, since you're only supplying the maximum allocation for weights, not activations. And space needed for activations is a difficult function exactly what layers end up on the device, so best you can do for now is just try some values and adjust based on which GPU ends up running out of memory first. The syntax is just `-gs 16.2,24` to use up to 16.2 GB on the first device, then up to 24 GB on the second. I find that works pretty well on 70B, but YMMV especially with lower group sizes.

**Comment by NickDatLe** [comment]
I didn't see the -gs flag, after setting it to 16.2,24 like you mentioned, it worked. Thank you!

 -- Perplexity:
 -- - Dataset: datasets/wikitext2_val_sample.jsonl
 -- - Chunks: 100
 -- - Chunk size: 2048 -> 2048
 -- - Chunk overlap: 0
 -- - Min. chunk size: 50
 -- - Key: text
 -- Tokenizer: Llama-2-70B-chat-GPTQ/tokenizer.model
 -- Model config: Llama-2-70B-chat-GPTQ/config.json
 -- Model: Llama-2-70B-chat-GPTQ/gptq_model-4bit--1g.safetensors
 -- Sequence length: 2048
 -- Tuning:
 -- --sdp_thd: 8
 -- --matmul_recons_thd: 8
 -- --fused_mlp_thd: 2
 -- Options: ['gpu_split: 16.2,24', 'perf', 'perplexity']
 ** Time, Load model: 4.34 seconds
 ** Time, Load tokenizer: 0.01 seconds
 -- Groupsize (inferred): None
 -- Act-order (inferred): no
 !! Model has empty group index (discarded)
 ** VRAM, Model: [cuda:0] 16,902.60 MB - [cuda:1] 17,390.74 MB
 ** VRAM, Cache: [cuda:0] 308.12 MB - [cuda:1] 320.00 MB
 -- Warmup pass 1...
 ** Time, Warmup: 1.33 seconds
 -- Warmup pass 2...
 ** Time, Warmup: 0.81 seconds
 -- Inference, first pass.
 ** Time, Inference: 1.24 seconds
 ** Speed: 1545.28 tokens/second
 -- Generating 128 tokens, 1920 token prompt...
 ** Speed: 17.07 tokens/second
 -- Generating 128 tokens, 4 token prompt...
 ** Speed: 21.84 tokens/second
 ** VRAM, Inference: [cuda:0] 317.16 MB - [cuda:1] 317.29 MB
 ** VRAM, Total: [cuda:0] 17,527.88 MB - [cuda:1] 18,028.04 MB
 -- Loading dataset...
 -- Testing 100 chunks..........
 ** Perplexity: 5.8741

**Comment by SinanAkkoyun** [comment]
> How do i split the model between the two GPUs? Does it matter than I'm running python 3.11?

Sorry, I forgot about that! I edited it now

**Comment by NickDatLe** [comment]
> > How do i split the model between the two GPUs? Does it matter than I'm running python 3.11?
> 
> Sorry, I forgot about that! I edited it now

All good, working now; I'm going to learn exllama more. Fascinating stuff!

**Comment by NickDatLe** [comment]
If it's ok with the mods, I'm going to leave this thread open in case someone posts a tutorial or have some great links to exllama.

**Comment by NickDatLe** [comment]
@SinanAkkoyun do you know what folks in the LLM community are using to communicate? Discord? Slack?

**Comment by SinanAkkoyun** [comment]
@NickDatLe Most that I know use Discord, however very decentralized over many servers

**Comment by NickDatLe** [comment]
> @NickDatLe Most that I know use Discord, however very decentralized over many servers

Ahh ok, I will join some discord servers. It seems "TheBloke" has a server and that person is very popular on the LLM leaderboard.

**Comment by turboderp** [comment]
Where is this? Invite me!

**Comment by cmunna0052** [comment]
@SinanAkkoyun Once the test_benchmark_inference.py script has finished successfully, is there an easy way to get the 70b chatbot running in a jupyter notebook?

**Comment by pourfard** [comment]
> PR

Can you share "example_chatbot_llama2chat.py" if it is possible?

**Comment by SinanAkkoyun** [comment]
@pourfard a PR is incoming today, I will implement it

**Comment by nktice** [comment]
First of all Thank You, exllama's working for me, while others do not...

I did some testing of a number of models with Sally riddle...
https://github.com/nktice/AMD-AI/blob/main/SallyAIRiddle.md
[ and here's my setup in case it's of benefit to other people -
https://github.com/nktice/AMD-AI ]
I did this by hand, through Oobabooga UI, and it took me a while. 

I'd like commands to run exllama from shell scripts ( such as a bash shell ).
So I went looking and was disappointed by the python files there...
I had hoped to find them respond with help info from the command line. 
"--help" or "-h" could return parameters and program purpose. 
[ As this thread was for documentation issues, seems like this would help. ]

**Comment by NickDatLe** [comment]
> 

send invite/link please!

**Comment by SinanAkkoyun** [comment]
https://discord.gg/theblokeai

Really awesome

**Comment by NickDatLe** [comment]
> https://discord.gg/theblokeai
> 
> Really awesome

Add me! nickdle

**Comment by SinanAkkoyun** [comment]
> Add me! nickdle

You need to join by clicking the link :)

**Comment by NickDatLe** [comment]
I invited you as a friend :)

**Comment by SinanAkkoyun** [comment]
@NickDatLe 
Oh you mean that, sure! I can't find you in my friend requests, what is your tag? :)

**Comment by NickDatLe** [comment]
> @NickDatLe Oh you mean that, sure! I can't find you in my friend requests, what is your tag? :)

nickdle, I sent a friend request.
