### ISSUE TITLE
Issue: RuntimeError: unable to mmap ... Cannot allocate memory (12)

### ISSUE THREAD

**Issue by jmoney7823956789378** [turboderp/exllama#193]
I just popped in a 3090 to sit warmly with the A4000s in my machine, and through a series of events, I was forced to make a clean ubuntu 22.04 installation.
I encountered this error as soon as I attempted to load 65/70B models on exllama. 13/33B models load without issue.
I haven't been able to find any information on this with my google-fu so maybe I'm slow.

```
(textgen) jm@gpu:/opt/text-generation-webui/repositories/exllama$ python test_benchmark_inference.py -d ../../models/TheBloke_airoboros-l2-70B-gpt4-1.4.1-GPTQ/ -p -gs 8,8,8,8,8
 -- Tokenizer: ../../models/TheBloke_airoboros-l2-70B-gpt4-1.4.1-GPTQ/tokenizer.model
 -- Model config: ../../models/TheBloke_airoboros-l2-70B-gpt4-1.4.1-GPTQ/config.json
 -- Model: ../../models/TheBloke_airoboros-l2-70B-gpt4-1.4.1-GPTQ/gptq_model-4bit-128g.safetensors
 -- Sequence length: 2048
 -- Tuning:
 -- --sdp_thd: 8
 -- --matmul_recons_thd: 8
 -- --fused_mlp_thd: 2
 -- Options: ['gpu_split: 8,8,8,8,8', 'perf']
Traceback (most recent call last):
  File "/opt/text-generation-webui/repositories/exllama/test_benchmark_inference.py", line 125, in <module>
    model = timer("Load model", lambda: ExLlama(config))
  File "/opt/text-generation-webui/repositories/exllama/test_benchmark_inference.py", line 56, in timer
    ret = func()
  File "/opt/text-generation-webui/repositories/exllama/test_benchmark_inference.py", line 125, in <lambda>
    model = timer("Load model", lambda: ExLlama(config))
  File "/opt/text-generation-webui/repositories/exllama/model.py", line 732, in __init__
    with safe_open(self.config.model_path, framework = "pt", device = "cpu") as f:
RuntimeError: unable to mmap 36652374536 bytes from file <../../models/TheBloke_airoboros-l2-70B-gpt4-1.4.1-GPTQ/gptq_model-4bit-128g.safetensors>: Cannot allocate memory (12)
```

**Comment by jmoney7823956789378** [comment]
As fate would have it, I accidentally had some strange memory allocation going on and I couldn't read.
Make sure you have enough RAM to load the model into VRAM :)

**Comment by TNT3530** [comment]
Just had this issue with a 70B model and 16GB RAM as well, latest commit
