### ISSUE TITLE
Support for StarCoder

### ISSUE THREAD

**Issue by bkutasi** [turboderp/exllama#64]
Hello there, 
upon loading StarCoder and its derivatives like WizardCoder the following error is thrown:
```
Traceback (most recent call last):
  File "/media/bkutasi/60824A4F824A29BC/Other_projects/exllama/test_benchmark_inference.py", line 114, in <module>
    config = model_init.make_config(args)
  File "/media/bkutasi/60824A4F824A29BC/Other_projects/exllama/model_init.py", line 97, in make_config
    config = ExLlamaConfig(args.config)
  File "/media/bkutasi/60824A4F824A29BC/Other_projects/exllama/model.py", line 40, in __init__
    self.pad_token_id = read_config["pad_token_id"]
KeyError: 'pad_token_id'
```
Since it's a different model architecture, `GPTBigCodeForCausalLM` instead of `LlamaForCausalLM` the config is pretty different, so pad_token_id and hidden_size and other parameters are missing. Am I loading it wrong, or these model types are not supported?

**Comment by turboderp** [comment]
StarCoder isn't currently supported, no. It's not a Llama model. See here for more: #14
