### ISSUE TITLE
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

### ISSUE THREAD

**Issue by zero-thermo** [turboderp/exllama#70]
Pop!_OS 20.04  
Python 3.8.10  
AMD 6800 XT GPU  

Installed with:  
```
pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cu118

pip install safetensors sentencepiece ninja

git clone https://github.com/turboderp/exllama
cd exllama
```

When running `python3 test_benchmark_inference.py -d /home/user1/models/ -p -ppl` or `python example_chatbot.py -d /home/user1/models/ -un "Jeff" -p prompt_chatbot.txt` I get the follow errors:  
```
Traceback (most recent call last):
  File "test_benchmark_inference.py", line 1, in <module>
    from model import ExLlama, ExLlamaCache, ExLlamaConfig
  File "/home/user1/bin/exllama/model.py", line 5, in <module>
    import cuda_ext
  File "/home/user1/bin/exllama/cuda_ext.py", line 42, in <module>
    exllama_ext = load(
  File "/home/user1/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1286, in load
    return _jit_compile(
  File "/home/user1/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1511, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/user1/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1603, in _write_ninja_file_and_build_library
    extra_ldflags = _prepare_ldflags(
  File "/home/user1/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1702, in _prepare_ldflags
    if (not os.path.exists(_join_cuda_home(extra_lib_dir)) and
  File "/home/user1/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2238, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
```

What am I doing wrong?

**Comment by jmoney7823956789378** [comment]
install ROCm version of pytorch
`pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.4.2`

**Comment by zero-thermo** [comment]
Thanks for pointing that out. I now have both ROCm and the ROCm version pf pytorch installed.   

However, running `python3 test_benchmark_inference.py -d /home/user1/models/ -p -ppl` still gives these errors:  
```
Traceback (most recent call last):
  File "test_benchmark_inference.py", line 3, in <module>
    from generator import ExLlamaGenerator
  File "/home/limbo/bin/exllama/generator.py", line 5, in <module>
    class ExLlamaGenerator:
  File "/home/limbo/bin/exllama/generator.py", line 30, in ExLlamaGenerator
    disallowed_tokens: list[int] or None
TypeError: 'type' object is not subscriptable
```

My models folder contains a mix of .bin models and directories cloned from [huggingface](https://huggingface.co/TheBloke/vicuna-13b-v1.3-GPTQ).  

What else am I missing?

**Comment by turboderp** [comment]
This is a Python error, though. Maybe to do with the fact that you're on Python 3.8? I'm developing on 3.10, so it may help to upgrade.

And for the `-d` argument to work you need a single .safetensors file, one config.json and one tokenizer.model in one directory. Or if you have multiple models in the same directory you can specify `-m`, `-c` and `-t` individually.

**Comment by zero-thermo** [comment]
Upgrading to python3.10 did the trick.  

Thank you all for the hard work on exllama and taking the time to help novices. This is a great community that is making AI more accessible for all.
