### ISSUE TITLE
Support for llama models with >2048 context?

### ISSUE THREAD

**Issue by Panchovix** [turboderp/exllama#74]
Hi there! As always, thanks for the amazing project.

I was trying to get to load Minotaur-15B (8192 max context), which it's the result of quantising to 4bit using GPTQ-for-LLaMa.
https://huggingface.co/TheBloke/minotaur-15B-GPTQ

At first, I was trying with ooba text webui, and got:

```
2023-06-19 15:07:54 INFO:Loading TheBloke_minotaur-15B-GPTQ...
2023-06-19 15:07:56 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "F:\ChatIAs\oobabooga\text-generation-webui\server.py", line 62, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "F:\ChatIAs\oobabooga\text-generation-webui\modules\models.py", line 65, in load_model
    output = load_func_map[loader](model_name)
  File "F:\ChatIAs\oobabooga\text-generation-webui\modules\models.py", line 277, in ExLlama_loader
    model, tokenizer = ExllamaModel.from_pretrained(model_name)
  File "F:\ChatIAs\oobabooga\text-generation-webui\modules\exllama.py", line 35, in from_pretrained
    config = ExLlamaConfig(str(model_config_path))
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\exllama\model.py", line 39, in __init__
    self.pad_token_id = read_config["pad_token_id"]
KeyError: 'pad_token_id'
```

Then, tried with exllama directly, and got;

```
(venv) PS F:\ChatIAs\exllama> python webui/app.py -d "F:\ChatIAs\oobabooga\text-generation-webui\models\TheBloke_minotaur-15B-GPTQ"
 -- Tokenizer: F:\ChatIAs\oobabooga\text-generation-webui\models\TheBloke_minotaur-15B-GPTQ\tokenizer.model
 -- Model config: F:\ChatIAs\oobabooga\text-generation-webui\models\TheBloke_minotaur-15B-GPTQ\config.json
 -- Model: F:\ChatIAs\oobabooga\text-generation-webui\models\TheBloke_minotaur-15B-GPTQ\4bit-128g.safetensors
 -- Sequence length: 2048
 -- Tuning:
 -- --matmul_recons_thd: 8
 -- --fused_mlp_thd: 2
 -- --sdp_thd: 8
 -- Options: []
Traceback (most recent call last):
  File "F:\ChatIAs\exllama\webui\app.py", line 133, in <module>
    config = model_init.make_config(args)
  File "F:\ChatIAs\exllama\model_init.py", line 97, in make_config
    config = ExLlamaConfig(args.config)
  File "F:\ChatIAs\exllama\model.py", line 39, in __init__
    self.pad_token_id = read_config["pad_token_id"]
KeyError: 'pad_token_id'
```

Is there any setting that I'm missing? Or are these models not compatible yet? Thanks!

**Comment by turboderp** [comment]
Minotaur isn't Llama, it's another StarCoder model. Although, apparently there's a lot of interest in those (#14, #62, #64) so maybe I need to bump up the priority a little bit. For now though, it isn't a supported architecture.
