### ISSUE TITLE
Support for models with 8-bit quants?

### ISSUE THREAD

**Issue by Panchovix** [turboderp/exllama#85]
Hi there, thanks for the all hard work.

I did a quant of a 30B model into 8bit instead of 4bit, but when trying to load the model into exllama, I get

```
2023-06-20 14:35:52 INFO:Loading Monero_WizardLM-Uncensored-SuperCOT-StoryTelling-30b-8bit...
2023-06-20 14:36:16 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "F:\ChatIAs\oobabooga\text-generation-webui\server.py", line 62, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "F:\ChatIAs\oobabooga\text-generation-webui\modules\models.py", line 65, in load_model
    output = load_func_map[loader](model_name)
  File "F:\ChatIAs\oobabooga\text-generation-webui\modules\models.py", line 277, in ExLlama_loader
    model, tokenizer = ExllamaModel.from_pretrained(model_name)
  File "F:\ChatIAs\oobabooga\text-generation-webui\modules\exllama.py", line 42, in from_pretrained
    model = ExLlama(config)
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\exllama\model.py", line 759, in __init__
    layer = ExLlamaDecoderLayer(self.config, tensors, f"model.layers.{i}", i, sin, cos)
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\exllama\model.py", line 440, in __init__
    self.self_attn = ExLlamaAttention(self.config, tensors, key + ".self_attn", sin, cos, self.index)
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\exllama\model.py", line 277, in __init__
    self.q_proj = Ex4bitLinear(config, self.config.hidden_size, self.config.num_attention_heads * self.config.head_dim, False, tensors, key + ".q_proj")
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\exllama\model.py", line 127, in __init__
    self.q4 = cuda_ext.ext_make_q4(self.qweight,
  File "F:\ChatIAs\oobabooga\text-generation-webui\repositories\exllama\cuda_ext.py", line 87, in ext_make_q4
    return make_q4(qweight,
RuntimeError: qweight and qzeros have incompatible shapes
```

Tried with exllama directly and got the same issue.

Then, I wondered if I did something wrong with the quant, so tried Guanaco 13B-8bit (https://huggingface.co/Monero/Guanaco-13b-Merged-8bit) and got the same issue.

**Comment by turboderp** [comment]
Well, like the readme says it's for 4-bit models. There's no support for 8-bit. I might do 3-bit at some point, but I don't see much of a reason to bother with 8-bit.

**Comment by Thireus** [comment]
I'd very much like 8bit support as well.

**Comment by bbecausereasonss** [comment]
> Well, like the readme says it's for 4-bit models. There's no support for 8-bit. I might do 3-bit at some point, but I don't see much of a reason to bother with 8-bit.

Curious, why don't you see a reason to support 8bit?
